Repository Azure/msi-acrpull, pull requests merged in 2020-08, with the labels that each got.

#15 Update README and add arch diagram
  README.md
  docs/msi-acrpull-flow.png
  docs/msi-acrpull.drawio
Labels: documentation

#23 Add cache to token retriever
  pkg/authorizer/authorizer.go
  pkg/authorizer/token_exchanger.go
  pkg/authorizer/token_exchanger_test.go
  pkg/authorizer/token_retriever.go
  pkg/authorizer/token_retriever_test.go
Labels: enhancement

#25 Allow user to specify a service account
  api/v1beta1/acrpullbinding_types.go
  config/crd/bases/msi-acrpull.microsoft.com_acrpullbindings.yaml
  config/webhook/manifests.yaml
  controllers/acrpullbinding_controller.go
  controllers/acrpullbinding_controller_test.go
  main.go
Labels: enhancement

#26 should continue removing finalizer when service account is not found
  controllers/acrpullbinding_controller.go
  controllers/acrpullbinding_controller_test.go
Labels: bug

#34 fix verbose error when acrpullbinding not found
  controllers/acrpullbinding_controller.go
  controllers/acrpullbinding_controller_test.go
Labels: bug

#32 Add cache to Go build workflow
  .github/workflows/go.yml
Labels: test improvement

#33 Enable controller HA by default
  config/manager/manager.yaml
Labels: enhancement

#31 Add Makefile target to build deploy artifacts
  Makefile
  README.md
  config/manager/kustomization.yaml
  deploy/latest/crd.yaml
  deploy/latest/deploy.yaml
Labels: documentation, test improvement
